/**
 * Set of sensitive path segments that indicate potential attacks or probing.
 * @type {Set<string>}
 */
const sensitivePaths = new Set([
  'env',
  'git',
  'ssh',
  'json',
  'wp-admin',
  'wp-login',
  'wp-json',
  'phpmyadmin',
  'phpinfo',
  'aws',
  'save',
  'php',
  'settings',
  'api',
  'db',
  'actuator',
  'powershell',
  'firebase',
  'admin',
  'hello.world',
  'backup',
  'htdocs',
  'config',
  'amplifyrc',
  'docker',
  'docker-compose',
  'credentials',
  'secrets',
  'serviceaccount',
  'private',
  'id_rsa',
  'id_dsa',
  'id_ecdsa',
  'id_ed25519',
  'gitlab',
  'github',
  'claude',
  'cursor',
  'anthropic',
  'codeium',
  'windsurf',
  'mcp',
  'graphql',
  'key',
  'secret',
  'token',
  'password',
  'certificate',
  'pem',
  'mailgun',
  'sendgrid',
  'sparkpost',
  'postmark',
  'mandrill',
  'gcloud',
  'aliyun',
  'tencent',
  'confluence',
  'laravel',
  'wordpress',
  'drupal',
  'jenkins',
  'grafana',
  'prometheus',
  'old',
  'bak',
  'zip',
  'tar',
  'gz',
  'rar',
  '7z',
]);

module.exports = (path) => {
  for (const sensitive of sensitivePaths) {
    if (path.includes(sensitive)) return true;
  }
  return false;
}